name: Device-Tree-Generator

on:
  workflow_dispatch:
    inputs:
      DEVICE_IMG:
        description: '(.img) file link'
        required: true
        default: 'https://youtu.be/pOpVtzysJf4?si=dNNTCnJHqDezTK7J'
      GITHUB_TOKEN:
        description: 'your github Access token (Optional)'
        required: true
        default: 'XXXXXXXXXXXXXXXXXXXXXXXXXX'

jobs:
  build:
    name: Device Tree Generator by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Getting tools ready 
      run: |
        python -m pip install git+https://github.com/pytube/pytube
        python pip install pytubefix
    
    - name: Downloading file
      run: |
        pytube ${{ github.event.inputs.DEVICE_IMG }}
        ls
        ls -la
        pwd
        
    - name: Set Build Date 
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
        name: env.BUILD_DATE
        tag_name: ${{ github.run_id }}
        body: |
